app_api/urls.py
from django.urls import path

import app_api.views.county as county
import app_api.views.state as state

from app_api.views.search import StateSuggestions, CountySuggestions
from app_api.views.chart import PercentileSeries, PointSeries


app_name = 'api'
urlpatterns = [
    # entities
    path('county/list/', county.ListAll.as_view()),
    path('state/list/', state.ListAll.as_view()),
    # search suggestions
    path('search/suggestions/state/<str:query>', StateSuggestions.as_view(), name='suggest_state'),
    path('search/suggestions/county/<str:query>', CountySuggestions.as_view(), name='suggest_county'),
    # async chart series
    path('chart/percentiles/<int:data_set_id>/', PercentileSeries.as_view(), name='chart_percentiles'),
    path('chart/points/<int:data_set_id>', PointSeries.as_view(), name='chart_points'),
]

hda_privileged/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'priv'
urlpatterns = [
    # home/dashboard
    path('home/<int:indicator>/',
         login_required(views.PrivDashboardView.as_view(), login_url='priv:login'),
         name='dashboardselected'),
    path('home/',
         login_required(views.PrivDashboardView.as_view(), login_url='priv:login'),
         name='dashboard1'),
    # creating new health indicators
    path('indicator/add/',
         login_required(views.HealthIndicatorCreate.as_view(), login_url='priv:login'),
         name='createIndicator'),
    # update an existing health indicator
    path('indicator/update/<int:post_pk>/',
         login_required(views.HealthIndicatorUpdate.as_view(),
                        login_url='priv:login'),
         name='updateIndicator'),
    # delete an existing health indicator
    path('indicator/delete/<int:post_pk>/',
         login_required(views.HealthIndicatorDelete.as_view(),
                        login_url='priv:login'),
         name='deleteIndicator'),
    # upload page
    path('upload/',
         login_required(views.UploadNewDataView.as_view(), login_url='priv:login'),
         name='uploadData'),
    # login/logout
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

hda_public/urls.py
from django.urls import path, register_converter
from hda_public.views import (
    HomeView,
    StateView,
    CountyView,
    HealthView,
    ChartView,
    SearchView,
)

# only successful method of import for this new view
from hda_public.views.location_selection import HealthStatePathView
from hda_public.converters import StateUSPSConverter, FIPS3Converter

# custom path converters to validate:
# - USPS 2-letter state codes:
register_converter(StateUSPSConverter, 'usps')
# - 3-digit FIPS codes.
register_converter(FIPS3Converter, 'fips3')

# we could acheive a prettier URL by slugifying the county names!
# https://stackoverflow.com/a/837835

urlpatterns = [
    # the home page:
    path('', HomeView.as_view(), name='home'),
    # a chart page that can show any counties given as a query parameter:
    path('chart/<int:indicator>', ChartView.as_view(), name='chart'),
    # location selection pages
    path('state/', StateView.as_view(), name='state'),
    path('state/<usps:short>', CountyView.as_view(), name='county'),
    path('state/<usps:short>/<fips3:fips>',
         HealthView.as_view(), name='metric'),
    path('state/indicator/<usps:short>/',
         HealthStatePathView.as_view(), name='selection_state_metric'),
    # search results page
    path('search/', SearchView.as_view(), name='search'),
]

health_data_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('hda_public.urls')),
    path('priv/', include('hda_privileged.urls')),
    path('api/', include('app_api.urls')),
    path('admin/', admin.site.urls),
]

hda_public/models.py
from django.db import models

# Create your models here.
'''
HERE'S TO TESTING HOW BRANCHING AND FORKING WORKS
'''

app_api/views/chart.py
import json

from app_api.views.get_json import GetJSON
from hda_privileged.models import Data_Set, US_County, US_State


class PercentileSeries(GetJSON):

    def get_data(self, data_set_id):
        # THROWS
        data_set = Data_Set.objects.get(pk=data_set_id)
        percentiles = data_set.percentiles.all().order_by('rank')
        spline_points = [(round(p.rank * 100, 2), p.value) for p in percentiles]
        config = {
            'name': 'Percentiles',
            'type': 'spline',
            'color': 'gray',
            'enableMouseTracking': False,
            'marker': {
                'enabled': False,
            },
            'data': spline_points,
        }
        return {'config': config}

class PointSeries(GetJSON):

    def try_get_county(self, fips_code):
        try:
            return US_County.objects.get(fips5=fips_code)
        except US_County.DoesNotExist:
            return None

    def try_get_point(self, data_set, county):
        return data_set.data_points.filter(county=county).first()

    def get_requested_counties(self):
        requested_state = self.request.GET.get('state', None)
        if requested_state:
            state = US_State.objects.get(pk=requested_state.upper())  # THROWS
            return ([county for county in state.counties.all().iterator()], [])
        else:
            requested_fips = self.request.GET.get('county', None)

            if requested_fips is None:
                raise Exception('Endpoint must be called with a state or county query string')

            fips_list = requested_fips.split(',')
            query_results = [(fips, self.try_get_county(fips)) for fips in fips_list]
            matched = [county for (_, county) in query_results if county]
            unmatched = [fips for (fips, county) in query_results if not county]
            return (matched, unmatched)


    def get_requested_points(self, data_set, counties):
        query_results = [(county, self.try_get_point(data_set, county)) for county in counties]
        points = [point for (_, point) in query_results if point]
        unmatched = [county for (county, point) in query_results if not point]
        return (points, unmatched)

    def point_to_dict(self, point):
        return {
            'x': round(point.rank * 100, 2),
            'y': round(point.value, 2),
            'name': point.county.name,
        }

    def get_data(self, data_set_id):

        data_set = Data_Set.objects.get(pk=data_set_id)  # THROWS

        (counties, unmatched_fips) = self.get_requested_counties()  # THROWS

        (points, unmatched_counties) = self.get_requested_points(data_set, counties)

        config = {
            'name': 'Values',
            'type': 'scatter',
            'color': 'darkred',
            'enableMouseTracking': True,
            'marker': {
                'radius': 3,
                'symbol': 'circle',
            },
            'tooltip': {
                'pointFormat': r'{point.name}<br/>p: <b>{point.x}%</b><br/>v: <b>{point.y}</b><br/>',
                'valueDecimals': 1,
            },
            'data': [self.point_to_dict(p) for p in points]
        }

        errors = dict()

        if len(unmatched_fips) > 0:
            errors['no_county'] = '; '.join(unmatched_fips)

        if len(unmatched_counties) > 0:
            errors['no_fips'] = '; '.join(
                [f"{county.name}, {county.state.short}" for county in unmatched_counties]
            )

        return {
            'config': config,
            'errors': errors,
        }

app_api/views/county.py
from django.db.models import Value, F
from django.db.models.functions import Concat

from app_api.views.list_all import ListEndpoint
from hda_privileged.models import US_County


class ListAll(ListEndpoint):

    model = US_County

    def get_values_queryset(self, request):
        return US_County.objects.values(
            'name', 'fips5', 'state',
            search=Concat('name', Value(' '), 'state__short')
        )

app_api/views/state.py
from django.db.models import Value, F
from django.db.models.functions import Concat

from app_api.views.list_all import ListEndpoint
from hda_privileged.models import US_State


class ListAll(ListEndpoint):

    model = US_State

    def get_values_queryset(self, request):
        return US_State.objects.values(
            'fips',
            usps=F('short'),
            name=F('full'),
            search=Concat('short', Value(' '), 'full')
        )

hda_public/views/homeview.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    '''
    Displays the home page. Since the home page is static, this is easy.
    '''
    template_name = 'hda_public/dashboard.html'

hda_public/views/location_selection.py
from django.views.generic import TemplateView, ListView

from hda_privileged.models import US_State, US_County, Health_Indicator

class StateView(ListView):
    template_name = 'hda_public/state.html'
    paginate_by = '15'
    model = US_State
    context_object_name = "states"

    def get_queryset(self):
        states = US_State.objects.all().order_by('full')
        return states

    def get_context_data(self, **kwargs):
        context = super(StateView, self).get_context_data(**kwargs)
        context['range'] = range(context['paginator'].num_pages)
        return context


class CountyView(ListView):
    template_name = 'hda_public/county.html'
    paginate_by = '15'
    model = US_County
    context_object_name = "counties"

    def get_context_data(self, **kwargs):
        context = super(CountyView, self).get_context_data(**kwargs)
        context['range'] = range(context['paginator'].num_pages)
        state_short_name = self.kwargs.get('short', None)

        if state_short_name is not None:
            context['state'] = US_State.objects.filter(short=state_short_name).first().full
            context['state_short_name'] = state_short_name

        return context

    def get_queryset(self):
        state_short_name = self.kwargs.get('short', None)
        counties = None

        if state_short_name is not None:
            associated_state = US_State.objects.filter(short=state_short_name).first()
            counties = associated_state.counties.order_by('name')

        return counties

# have identified a potential problem:
# assume 2 data sets for 1 indicator, one 2017 and one 2018
# let's say the 2017 data set includes county X, but set 2018 does NOT include county X
# when we collect indicators that contain county X, we will find the 2017 data set through
# the 2017 data point for county X, and hence find our indicator object.

# when we go to the chart view, we pass it 3 pieces of information: state, county, and indicator
# the chart view then looks up the latest data set for the given indicator (which will be the 2018 one)
# the data set that is plotted will not include county X, but the URL specifies that we should
# highlight county X.

# hmmm.

class HealthView(TemplateView):
    template_name = 'hda_public/health_indicator.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        fips = self.kwargs.get('fips', None)
        state_short = self.kwargs.get('short', None)

        if fips is not None and state_short is not None:
            # get the state the user wants
            state = US_State.objects.get(short=state_short.upper())
            # get the county the user wants
            county = state.counties.get(fips=fips)
            # make a list of every data set containing a data point connected to this county,
            # by starting with the county's data points and going backwards.
            # the 'select_related' does *not* affect the result of the query, only how many database queries are required.
            available_data_sets = [dp.data_set for dp in county.data_points.all().select_related('data_set')]
            # several data sets may be for the same indicator (perhaps different datasets for different years).
            # this extracts the indicator from each dataset into a list, then puts that list into a python set object,
            # which can remove the duplicates for us.
            unique_indicators = set([ds.indicator for ds in available_data_sets])
            # pack up the context - including whole objects so we can use multiple properties in the template
            context['state'] = state
            context['county'] = county
            context['indicators'] = unique_indicators
        else:
            context['error'] = 'Missing a valid state or county identifier in the URL for this page'

        return context

# User chose state path


class HealthStatePathView(TemplateView):
    template_name = 'hda_public/health_indicator.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        state_short = self.kwargs.get('short', None)

        # user selected state from dashboard
        if state_short is not None:
            # get the state the user wants
            chosen_state = US_State.objects.get(short=state_short.upper())
            counties = US_County.objects.filter(state=chosen_state)
            for county in counties:
                dp = county.data_points
            # make a list of every data set containing a data point connected to counties in this state,
            # by starting with the county data points and going backwards.
            # the 'select_related' does *not* affect the result of the query, only how many database queries are required.
            available_data_sets = [
                dp.data_set for dp in county.data_points.all().select_related('data_set')]
            # several data sets may be for the same indicator (perhaps different datasets for different years).
            # this extracts the indicator from each dataset into a list, then puts that list into a python set object,
            # which can remove the duplicates for us.
            unique_indicators = set(
                [ds.indicator for ds in available_data_sets])
            # pack up the context - including whole objects so we can use multiple properties in the template
            context['state'] = chosen_state
            context['county'] = counties
            context['indicators'] = unique_indicators
        else:
            context['error'] = 'Missing a valid state or county identifier in the URL for this page'

        return context

hda_public/views/searchview.py
from django.views.generic import TemplateView

from hda_privileged.models import US_County, US_State

class SearchView(TemplateView):
    template_name = 'hda_public/search_results.html'

    def find_county_results(self, query):
        # Orders results first by state, then by name. This does not put the most relevant result
        # first, but groups results from the same state together, which may make them easier to scan through?
        matches = US_County.objects.filter(search_str__icontains=query).order_by('state', 'name')
        # truncate to no more than 100 results!
        return list(matches.iterator())[:100]

    def find_state_results(self, query):
        name_matches = US_State.objects.filter(full__istartswith=query)
        abbrv_matches = US_State.objects.filter(short__istartswith=query)
        name_set = set(name_matches.iterator())
        abbrv_set = set(abbrv_matches.iterator())
        all_set = name_set | abbrv_set  # set union
        return sorted(all_set, key=lambda s: s.full)

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)

        query_str = self.request.GET.get('query', '')

        if len(query_str) < 1:
            context['error'] = 'Please provide some text to search with'
            return context

        context['query'] = query_str

        context['counties'] = self.find_county_results(query_str)
        context['states'] = self.find_state_results(query_str)

        return context

hda_public/templates/hda_public/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <style>
        img.a {
            vertical-align: middle;
        }
    </style>
    <!-- Meta stuff, from: https://getbootstrap.com/docs/3.3/getting-started/#template -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--
    Bootstrap's base CSS via CDN - previously we hosted this ourselves but
    I think I've been converted: https://stackoverflow.com/q/24132951
    NOTE that this is Bootstrap 3.3.x!
    -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">

    <!-- FontAwesome icon fonts -->
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.3.1/css/solid.css"
          integrity="sha384-VGP9aw4WtGH/uPAOseYxZ+Vz/vaTb1ehm1bwx92Fm8dTrE+3boLfF1SpAtB1z7HW"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.3.1/css/fontawesome.css"
          integrity="sha384-1rquJLNOM3ijoueaaeS5m+McXPJCGdr5HcA03/VHXxcp2kX2sUrQDmFc3jR5i/C7"
          crossorigin="anonymous">

    <!-- Our CSS on top of Bootstrap -->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet">
    {% comment %} <script src="{% static 'js/graph.css'%}"></script> {% endcomment %}
    {% comment %} {% block jqurey %}{% endblock %} {% endcomment %}

  <script type="text/javascript">

            function Redirect() {
               window.location="{% url 'priv:dashboard1' %}";
            }

            function TimeoutNow() {
            setTimeout('Redirect()', 3000);
            }
  </script>

   <title> {% block title %}{% endblock %} </title>


</head>
<body>
<div class="container">
    <h1></h1>
    {% block nav %}
    <nav class="navbar navbar-default navBackground">
        <div class="container-fluid">
            <div class="navbar-header">
                <!-- brand image icon (ETSU shield) -->
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="/static/img/eshield.png"
                        alt="ETSU shield logo"
                        width="45"
                        height="45" />
                </a>
                <!-- brand texts -->
                <div class="navbar-brand-text navbar-left">
                    <h1>College of Public Health</h1>
                    <h2>Indicator Visualization Tool</h2>
                </div>
                <!-- menu button that shows when collapsed -->
                <button type="button"
                        class="navbar-toggle collapsed"
                        data-toggle="collapse"
                        data-target="#menuDropdown"
                        aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- items that collapse on mobile -->
            <div class="collapse navbar-collapse" id="menuDropdown">

                <!-- search box -->
                <form class="navbar-form navbar-left" action={% url 'search' %} method="GET">
                    <div id='search_container' class="form-group">
                        <input id="search_box"
                            autocomplete="off"
                            name="query"
                            type="search"
                            class="form-control"
                            placeholder="Search counties..."/>
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <!-- home button -->
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav navbar-nav navbar--right">
                        <a href="{% url 'home' %}"> <i class="fa fa-home"
                                        style="font-size:20px"></i> Home</a>

                    </li>
                </ul>
            </div>
        </div><!-- /container -->
    </nav><!-- /navbar-default -->
    {% endblock %}
</div><!-- /container -->

<div class="container">

    {% block content %}

    {% endblock %}
</div>

<hr>
{% block footer %}
    <footer class="application-footer">
        <div class="container" style="bottom:0">
            <a href="{% url 'priv:login' %}" style="float:right; color:MidnightBlue"><i class="fas fa-user"></i>
                Admin</a>
            <h4 style="float:left; font-size:10px">ETSU College of Public Health | 104 Lamb Hall | Box 70623 | Johnson
                City, TN 37614 | Tel.: 423-439-4243 | Fax.: 423-439-5238</h4>
        </div>
    </footer>
{% endblock %}

<!-- Bootstrap's JS (again, note that this is 3.3.x) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js'></script>

<!-- Place for child pages to add more Javascript if needed -->
{% block extra_scripts %}
{% endblock %}


<!-- autocomplete for search -->
<!-- this loads the library: typeahead.js + bloodhound.js -->
<script src="{% static 'js/typeahead.bundle.js' %}"></script>
<!-- this loads a function that sets up our instance of the library -->
<script src="{% static 'js/typeahead_config.js' %}"></script>
<!-- this executes that function. it requires some URLs that only the template generator knows
the canonical version of, so we construct them here and pass them in as strings -->
<script>
    const typeahead_cfg = {
        prefetch: {
            county: "{% static 'prefetch/county.json' %}",
            state: "{% static 'prefetch/state.json' %}"
        },
        remote: {
            county: "{% url 'api:suggest_county' '%Q%' %}",
            state: "{% url 'api:suggest_state' '%Q%' %}",
            wildcard: "{{ '%Q%' | urlencode }}",
        }
    };
    TypeaheadSetup.init(typeahead_cfg);
</script>
</body>
</html>

hda_public/templates/hda_public/chart.html
{% extends "hda_public/base.html" %}
{% comment %}
Template for the primary chart page: shows a single, large chart that plots the percentile curve
for a single data set, along with scatter plot points for a specific county or counties.

Context:
  Required:
    indicator (Health_Indicator)
      used for the name and ID of the health indicator being plotted
    year (int)
      displays the year the data set is from
    counties (List FIPS-5)
      list of 5-digit FIPS codes (str) of counties to include in plot

  Optional:
    data_set_id (int)
      ID of Data Set to plot
      (If this is missing, the page just shows a "woops, sorry" message)
    parent_state (USPS)
      If present, used to include a button that links to a plot of all counties in that state
    messages (List django.contrib.messages)
      Messages added by the messages framework
    place_name (string)
      Used to augment the chart title with a location name if a single county or state is being plotted

Spring 2019 - Jean-Marie Nshimiyimana, Matthew Seiler
{% endcomment %}


{% comment %} Need this to use the "static" template tag later in the file {% endcomment %}
{% load staticfiles %}

{% block title %}{{indicator.name}} ({{year}}){% endblock %}

{% block content %}

{% comment %} Contains the chart if a data set ID was provied {% endcomment %}
<div class="row">
  {% if data_set_id %}
  <div id="chartdiv"></div>
  
    {% if parent_state %}    
      <p>See all counties in this state: <a role="button"
            href="{% url 'chart' indicator.id %}?state={{ parent_state | urlencode }}"
            class="btn btn-default btn-sm">{{ indicator.name }}: {{parent_state}}</a></p>
    {% else %}
    <!-- Future development -->
      <p>See a county in this state: <a role="button"
          href="#"
          class="btn btn-default btn-sm">{{ indicator.name }}: {{state.short}}</a></p>     
    {% endif %}    
  
  {% else %}
  <p>Please select a state and health indicator to display data for</p>
  {% endif %}
  
</div>

{% comment %} Contains any alert/notification messages {% endcomment %}
<div class="row">
  <div class='form-group'>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <div
            class="alert alert-{{ message.level_tag }}"
            role="alert">
            {{ message }}
          </div>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
</div>

{% endblock %}


{% block extra_scripts %}

{% comment %} Highchart script CDN  {% endcomment %}
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<!-- optional, but adds more features -->
<script src="http://code.highcharts.com/modules/offline-exporting.js"></script>
<script src="http://code.highcharts.com/modules/export-data.js"></script>

{% comment %} Our Highcharts configuration and loading code {% endcomment %}
<script src="{% static 'js/highcharts_single.js' %}"></script>

{% if data_set_id %}
<script>
(function(){
  /*{% comment %}
  Generate the URL we will request the percentile spline series from.
  {% endcomment %}*/
  const percentile_url = "{% url 'api:chart_percentiles' data_set_id %}";

  /*{% comment %}
  Generate the URL we will request the data point scatter series from.
  Converts the counties list into a single comma-separated string, then
  appends it to the base URL for the endpoint.
  {% endcomment %}*/
  const county_list = "{{ counties | join:',' }}";
  const point_url = "{% url 'api:chart_points' data_set_id %}?county=" + county_list;

  /*{% comment %}
  Generate the title for the chart
  {% endcomment %}*/
  const title = "{{indicator.name}} ({{year}})" {% if place_name %} + " {{place_name}}"{% endif %};

  SingleChart.init(
    'chartdiv',
    percentile_url,
    point_url,
    title
  );
}());
</script>
{% endif %}

{% endblock %}

hda_public/templates/hda_public/county.html
{% extends 'hda_public/base.html' %}
{%block title%}Counties{%endblock%}
{% block content %}
	<div id="container">
        <a href="/state"> << View all states </a> <h3>{{ state}} </h3>
	<table class="table table-hover">
		<thead>
			<tr>
            <th scope ="col">Fips Code</th>
			<th scope="col">Name</th>
			</tr>
		</thead>
        <tbody>
        {% for county in counties %}
				<tr>
                    <td>{{ county.fips }}</td>
                    <td><a href="/state/{{ state_short_name }}/{{ county.fips }}?choice=county">{{ county.name }}</a></td>
                </tr>
        {% endfor %}
        </tbody>
        </table>

        <ul class="pagination center-align">
        {% if page_obj.has_previous %}
            <li class="">
                <a href="/state/{{ state_short_name }}?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
        {% endif %}
        {% for i in range %}
            <li class=" {% if page_obj.number == forloop.count %}activate{% endif %}">
                <a href="/state/{{ state_short_name }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
            </li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="">
                <a href="/state/{{ state_short_name }}?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% endif %}
    </ul>
    </div>
{% endblock %}

hda_public/templates/hda_public/dashboard.html
{% extends 'hda_public/base.html' %}

{% block title %} CPH Indicator Visualization Tool {% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>Find a Location</h1>
    <p>
        This site provides visualization and ranking of national public health indicators for counties in the United States.
        Find your county and select an indicator to see how it compares to other counties in the nation!
    </p>
    <p>
        <a class="btn btn-primary btn-lg" href="{% url 'state' %}?choice=county" role="button" name="selected" value="county">Find a county</a>
        <a class="btn btn-primary btn-lg" href="{% url 'state' %}?choice=state" role="button" name="selected" value="state">Find a state</a>
    </p>
</div>

{% endblock %}

hda_public/templates/hda_public/health_indicator.html
{% extends 'hda_public/base.html' %}
{%block title%}Health Indicators{%endblock%}
{% block content %}
	<div id="container">
    <h3> Health Indicators </h3>

    {% if error %}
    <div class="alert alert-warning" role="alert">
        {{ error }}
    </div>
    {% else %}
    
    {% if 'choice=county' in request.GET.urlencode %}
        <h4>Indicators available for {{county.name}}, {{ state.short }}</h4>
    <!-- Eliminate comma and empty county name space -->
    {% else %}
        <h4>Indicators available for {{ state.short }}</h4>
    {% endif %}

    <div class="list-group">
        {% for indicator in indicators %}
            <!-- determine if user chose county or state path from dashboard -->
            {% if 'choice=county' in request.GET.urlencode %}
                <a href="{% url 'chart' indicator.id %}?county={{county.fips5}}" class="list-group-item">{{ indicator.name }}</a>
            {% else %}
                <a href="{% url 'chart' indicator.id %}?state={{ state.short }}" class="list-group-item">{{ indicator.name }}</a>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}

{% endblock %}

hda_public/templates/hda_public/search_results.html
{% extends 'hda_public/base.html' %}

{% block title %}Results{% endblock %}

{% block content %}

{% if counties or states %}

  <h1>Search results</h2>
  <p>For &quot;{{ query }}&quot;</p>

  <div class="row">

  {% if counties %}
    <div class="col-md-4">
      <h2>Counties</h2>
      <ul>
      {% for county in counties %}
        <li>
          <a href="{% url 'metric' county.state.short county.fips %}">{{ county.name }}, {{ county.state.short}}</a>
        </li>
      {% endfor %}
      </ul>
    </div>
  {% endif %}

  {% if states %}
    <div class="col-md-4">
      <h2>States</h2>
      <ul>
      {% for state in states %}
        {% comment %} TODO: link to page where we can choose an indicator for a state! {% endcomment %}
        <li>
            <a href="{% url 'state' %}">{{ state.full }} ({{state.short}})
        </li>
      {% endfor %}
      </ul>
    </div
  {% endif %}

  </div><!-- /end row-->

{% elif error %}
  <div class="alert alert-danger" role="alert">
    {{ error }}
  </div>

{% else %}
  <h1>No results</h1>
  <p>No states or counties found matching &quot;{{ query }}&quot;</p>

{% endif %}

{% endblock %}

hda_public/templates/hda_public/table.html
{% extends 'hda_public/base.html' %}
{%block title%}Health Indicators{%endblock%}
{% block content %}
	<div id="container">
	<table class="table table-hover">
		<thead>
			<tr>
			<th scope="col"></th>
			<th scope="col">County</th>
			<th scope="col">Value</th>
			<th scope="col">Percentile</th>
			<th scope="col">Data set</th>
			</tr>
		</thead>
		
		<tbody>
			{% for dataset in datasets %}
				<tr>
					<td>{{ dataset.id }}</td>
					<td>{{ dataset.county.name }}</td>
					<td>{{ dataset.value }}</td>
					<td>{{ dataset.percentile }}</td>
					<td>{{ dataset.data_set.indicator.name }}</td>
				</tr>
			{% endfor %}
		</tbody>

	</table>
{% endblock %}