app_api/urls.py
from django.urls import path

import app_api.views.county as county
import app_api.views.state as state

from app_api.views.search import StateSuggestions, CountySuggestions
from app_api.views.chart import PercentileSeries, PointSeries


app_name = 'api'
urlpatterns = [
    # entities
    path('county/list/', county.ListAll.as_view()),
    path('state/list/', state.ListAll.as_view()),
    # search suggestions
    path('search/suggestions/state/<str:query>', StateSuggestions.as_view(), name='suggest_state'),
    path('search/suggestions/county/<str:query>', CountySuggestions.as_view(), name='suggest_county'),
    # async chart series
    path('chart/percentiles/<int:data_set_id>/', PercentileSeries.as_view(), name='chart_percentiles'),
    path('chart/points/<int:data_set_id>', PointSeries.as_view(), name='chart_points'),
]

hda_privileged/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'priv'
urlpatterns = [
    # home/dashboard
    path('home/<int:indicator>/',
         login_required(views.PrivDashboardView.as_view(), login_url='priv:login'),
         name='dashboardselected'),
    path('home/',
         login_required(views.PrivDashboardView.as_view(), login_url='priv:login'),
         name='dashboard1'),
    # creating new health indicators
    path('indicator/add/',
         login_required(views.HealthIndicatorCreate.as_view(), login_url='priv:login'),
         name='createIndicator'),
    # update an existing health indicator
    path('indicator/update/<int:post_pk>/',
         login_required(views.HealthIndicatorUpdate.as_view(),
                        login_url='priv:login'),
         name='updateIndicator'),
    # delete an existing health indicator
    path('indicator/delete/<int:post_pk>/',
         login_required(views.HealthIndicatorDelete.as_view(),
                        login_url='priv:login'),
         name='deleteIndicator'),
    # upload page
    path('upload/',
         login_required(views.UploadNewDataView.as_view(), login_url='priv:login'),
         name='uploadData'),
    # login/logout
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

health_data_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('hda_public.urls')),
    path('priv/', include('hda_privileged.urls')),
    path('api/', include('app_api.urls')),
    path('admin/', admin.site.urls),
]

hda_privileged/forms.py
from django import forms
from django.forms import ModelForm

from .models import Health_Indicator
from .upload_reading import UPLOAD_FORMAT_CHOICES, CHOICE_NAME


class HealthIndicatorForm(ModelForm):
    class Meta:
        model = Health_Indicator
        fields = ['name']
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'e.g. \'Poor physical health days\'',
                    'size': 100,
                }
            )
        }


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': "form-control", 'placeholder': "Username"}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': "form-control", 'placeholder': "Password"}
        )
    )


# Not using a ModelForm because this needs to include data for
# both Document and Data_Set model classes - we could make an
# additional Model class (e.g. NewDataUpload entity) with the
# right fields and then create a ModelForm from that, but that
# seems like an extra step.
class UploadNewDataForm(forms.Form):
    """
    Form subclass for displaying an upload form for new data sets.
    """
    file = forms.FileField(
        label='Data File',
        help_text='File containing data in CSV format'
    )

    column_format = forms.ChoiceField(
        label='CSV file format',
        help_text='What columns to use to identify counties in the uploaded CSV file',
        widget=forms.RadioSelect,
        choices=UPLOAD_FORMAT_CHOICES,
        required=True,
        initial=CHOICE_NAME
    )

    # TODO #
    # This needs to be required once we have a way to create new ones #
    indicator = forms.ModelChoiceField(
        queryset=Health_Indicator.objects.all(),
        label='Health indicator',
        help_text='The health indicator/metric that this file contains data for',
        required=False
    )

    source = forms.CharField(
        label='Data source',
        help_text='The source/provenance of the data',
        required=False,
        widget=forms.Textarea(attrs={'rows': 3})
    )

    # TODO #
    # The default value should not be hardcoded!
    year = forms.IntegerField(
        label='Data year',
        help_text='Year this data is from',
        initial=2018,
        min_value=1000,
        max_value=9999
    )

hda_privileged/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, get_user, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Error message for user if trying to delete a foreign key
from django.db.models.deletion import ProtectedError
import json

from .forms import LoginForm, UploadNewDataForm, HealthIndicatorForm
from .models import Document, Data_Set, Data_Point, Percentile, Health_Indicator
from .percentile import get_percentiles_for_points, assign_percentiles_to_points
from .upload_reading import read_data_points_from_file


# ------------------------------------------------
# The user_log-in function will handle the log in
# functionality and redirect the loggedin user to
# desired page
# ------------------------------------------------
def user_login(request):
    form = LoginForm()
    next = ""
    if request.GET:
        next = request.GET['next']
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    # The 'sample' routing will be changed to the desired landing page
                    # that will be displayed after authenticated user logs in
                    # If there is no next page to rout to, the routing will go to the
                    # Default landing page
                    if next == "":
                        return redirect(reverse('priv:dashboard1'))
                    else:
                        # If there is a next page, the routing will automatical go to the
                        # next page after a user is authenticated
                        return redirect(next)
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    args = {'form': form, 'next': next}
    return render(request, 'hda_privileged/login.html', args)


def logout_view(request):
    logout(request)
    return redirect('priv:login')


class HealthIndicatorCreate(CreateView):
    template_name = 'hda_privileged/create_metric.html'
    model = Health_Indicator
    form_class = HealthIndicatorForm
    success_url = reverse_lazy('priv:dashboard1')


class HealthIndicatorUpdate(UpdateView):
    model = Health_Indicator
    fields = ('name',)
    template_name = 'hda_privileged/update_metric_form.html'
    pk_url_kwarg = 'post_pk'

    # Django requires this method when using the UpdateView param above
    def get_success_url(self):
        return reverse_lazy('priv:dashboard1')


class HealthIndicatorDelete(DeleteView):
    model = Health_Indicator
    fields = ('name',)
    template_name = 'hda_privileged/delete_metric.html'
    pk_url_kwarg = 'post_pk'

    # This method uses json to prevent the user from dealing with a long error list page
    # in the event of a protected indicator
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            data = 'The chosen indicator has been deleted.'
        except ProtectedError:
            data = 'The Health Indicator is tied to existing datasets and cannot be deleted.'
        return HttpResponse(json.dumps(data), content_type="application/json")

    def get_success_url(self):
        return reverse_lazy('priv:dashboard1')


class PrivDashboardView(TemplateView):
    template_name = 'hda_privileged/privdashboard.html'

    def get_context_data(self, **kwargs):
        # call super to get the base context
        context = super().get_context_data(**kwargs)

        # get indicators for left side of view
        indicators = Health_Indicator.objects.all()
        context['indicators'] = indicators

        # did the URL specify an indicator? Get indicator and save in context
        selected_id = self.kwargs.get('indicator', None)
        # now check if that ID is valid - is there an indicator with that ID?
        # use filter + first because get will throw an error if the object doesn't exist;
        # whereas this will have a value of None if it doesn't exist
        selected_indicator = indicators.filter(pk=selected_id).first()
        context['selected_indicator'] = selected_indicator

        if selected_indicator is not None:
            # if a valid indiactor was selected, only show datasets from that indicator
            context['indicator_message'] = f'Data sets for {selected_indicator.name}'
            context['datasets'] = selected_indicator.data_sets.all()
        else:
            # otherwise, show all the data sets
            context['indicator_message'] = 'Data sets for all indicators'
            context['datasets'] = Data_Set.objects.all()

        return context


class UploadNewDataView(View):
    form_class = UploadNewDataForm
    template_name = 'hda_privileged/upload_metric.html'
    file_field_name = 'file'

    def _get_uploaded_file(self, request):
        return request.FILES[self.file_field_name]

    def _check_file_ext(self, request):
        uploaded_file = self._get_uploaded_file(request)

        okay = uploaded_file is not None and \
               uploaded_file.name.lower().endswith(('.csv'))

        if not okay:
            messages.warning(request, "Error in file upload, file was not CSV")

        return okay

    def _handle_form_submission(self, request, form):
        myfile = self._get_uploaded_file(request)

        # create a Document class instance
        doc = Document(
            file=myfile,
            source=form.cleaned_data['source']
        )

        # add a user if we have one
        if request.user.is_authenticated:
            doc.user = get_user(request)

        # this saves the file in the directory specified
        # in the Document model FileField.upload_to attribute
        # and saves the rest of the model in the database
        doc.save()
        messages.success(request, "Document uploaded successfully")

        # Create and save a Data Set here! ##
        indicator = form.cleaned_data['indicator']
        year = form.cleaned_data['year']

        data_set = Data_Set(
            indicator=indicator,
            year=year,
            source_document=doc
        )

        data_set.save()

        format_choice = form.cleaned_data['column_format']
        doc.file.open(mode='rt')
        # read_data_points_from_file returns two values: successful_datapoints, and unsuccessful datapoints
        successful_data_points, invalid_counties_and_states = read_data_points_from_file(doc.file, format_choice, data_set)
        doc.file.close()

        # calculate the percentile-values for this data set
        percentile_values = get_percentiles_for_points(successful_data_points)

        # assign a percentile to each data point
        assign_percentiles_to_points(successful_data_points, percentile_values)

        # transform our list of tuples List<(P, PV)> into a list of Percentile model objects
        percentile_models = [Percentile(rank=p, value=pv, data_set=data_set) for (p, pv) in percentile_values]

        # save all the data points and percentile values using bulk_create, for speed
        Data_Point.objects.bulk_create(successful_data_points)
        Percentile.objects.bulk_create(percentile_models)
        #

        # This is mostly for debugging, but it's a useful example of using the messages API
        messages.info(request, f"Indicator was {indicator!s}")

        return invalid_counties_and_states

    def get(self, request, *args, **kwargs):
        # unbound form
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        # bind the form
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid() and self._check_file_ext(request):
            # Is there a Django-y way of adding more validation?
            invalid_counties_and_states = self._handle_form_submission(request, form)

        return render(request, self.template_name, {'form': form,'invalid_counties_and_states':invalid_counties_and_states})


class HealthIndicator(TemplateView):
    model = Health_Indicator
    template_name = 'hda_privileged/create_metric.html'
    context_object_name = 'all_indicators_created'

hda_privileged/templates/hda_privileged/base.html
{% load staticfiles %}
{%block header %}
<!DOCTYPE html>
<html>
<head>
  <!-- Meta stuff, from: https://getbootstrap.com/docs/3.3/getting-started/#template -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--
    Bootstrap's base CSS via CDN - previously we hosted this ourselves but
    I think I've been converted: https://stackoverflow.com/q/24132951
    NOTE that this is Bootstrap 3.3.x!
    -->
  <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- FontAwesome icon fonts -->
   <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.3.1/css/solid.css"
    integrity="sha384-VGP9aw4WtGH/uPAOseYxZ+Vz/vaTb1ehm1bwx92Fm8dTrE+3boLfF1SpAtB1z7HW"
    crossorigin="anonymous">
   <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.3.1/css/fontawesome.css"
    integrity="sha384-1rquJLNOM3ijoueaaeS5m+McXPJCGdr5HcA03/VHXxcp2kX2sUrQDmFc3jR5i/C7"
    crossorigin="anonymous">

    <!-- Our CSS on top of Bootstrap -->
   <link href="{% static 'css/theme.css'%}" rel="stylesheet">
</head>
{% endblock %}

<body>
<div class="container">

{% block nav %}
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav">
      <li><a href="{% url 'priv:dashboard1' %}"><i class="fa fa-home" style="font-size:20px"></i></a></li>
      <li></li><li></li>
      <li style="font-size:20px"><a href="https://www.etsu.edu/cph/">CPH</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
      <li><a href="#" style="font-size:20px">Welcome {{request.user.username}}!</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" style="font-size:20px"></i><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'priv:createIndicator' %}">Create Health Indicator</a></li>
            <li><a href="{% url 'priv:uploadData' %}">File Upload</a></li>
            <li><a href="{% url 'priv:logout' %}">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% endblock %}

    {% block content %}
    {% endblock %}

</div>

	<hr>
	<footer class="application-footer">
		<div class="container" style="bottom:0">

		</div>
	</footer>
</body>
</html>

hda_privileged/templates/hda_privileged/base_minimal.html
{% load staticfiles %}
{% block header %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">

  <link href="{% static 'css/theme.css'%}" rel="stylesheet">

  <title>{%block title%}{%endblock%}</title>
</head>
{% endblock %}
<body>
  {% block content %}
  {% endblock %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
    crossorigin="anonymous"></script>

  <!-- Place for child pages to add more Javascript if needed -->
  {% block extra_scripts %}
  {% endblock %}
</body>
</html>

hda_privileged/templates/hda_privileged/create_metric.html
{% extends 'hda_privileged/base.html' %}

{% block content %}
{% comment %} Wrap the form in a panel for appearance {% endcomment %}
<div class='panel panel-primary'>

  <div class="panel-heading">
    <h3 class="panel-title">Create a new health indicator</h3>
  </div>

  <div class="panel-body">
    <p>Adding a health indicator allows you to upload new data sets for that indicator. Health indicator names should be unique.</p>

    <form class='form-inline' method='POST'>
      {% csrf_token %}

      {% comment %} Hidden fields, if any {% endcomment %}
      {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
      {% endfor %}

      {% comment %} Errors that aren't specific to one field {% endcomment %}
      {% if form.non_field_errors %}
        {% for err in form.non_field_errors %}
        <div class="alert alert-danger" role="alert">{{ err | escape }}</div>
        {% endfor %}
      {% endif %}

      {% comment %} Now visible fields {% endcomment %}
      {% for field in form.visible_fields %}

      <div class={% if field.errors %} "form-group has-error" {% else %} "form-group" {% endif %}>

        <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}

        {% if field.help_text %}
        <span class="help-block">{{ field.help_text }}</span>
        {% endif %}

        {% if field.errors %}
          {% for err in field.errors %}
          <p class="text-danger">{{ err | escape }}</p>
          {% endfor %}
        {% endif %}

      </div>
      {% endfor %}

      <input class='btn btn-primary' type='submit' value='Add'/>
     <input class='btn btn-primary' type="button" value='Cancel' onclick="window.history.back()"/>
    </form>
  </div>
</div>
{% endblock %}

hda_privileged/templates/hda_privileged/delete_metric.html
{% extends 'hda_privileged/base.html' %}

{% block content %}

{% comment %} Wrap the form in a panel for appearance {% endcomment %}
<div class='panel panel-primary'>

  <div class="panel-heading" style="background-color:#69899f;color: #d7e2e9;">
    <h3 class="panel-title">Delete a health indicator</h3>
  </div>

  <div class="panel-body">
    <h4>Deleting a health indicator will permanently remove the indicator from data storage.</h4>
    <form method="post" class='form-inline'>{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>

    <br/>
        <br/>    
        <button type="submit" class="btn btn-success" style="background-color:#69899f;color: #d7e2e9;">Confirm Delete</button>
        <input class='btn btn-primary' type="button"  style="background-color:#69899f;color: #d7e2e9;" value='Cancel' onclick="window.history.back()"/>
    </form>
  </div>
</div>  
{% endblock %}

hda_privileged/templates/hda_privileged/login.html
{% extends 'hda_privileged/base_minimal.html' %}

{%block title%}Login{%endblock%}

{% block content %}

<div class='container' style="margin-top: 10em;">
    <div class="signin-row row">
        <div class="col-md-offset-3 col-md-6">
            <div class="container-signin panel panel-info">
                {% if next %}
                    <form action="./?next={{next}}" method="post" id='loginForm' class='form-horizontal' autocomplete='off'>
                {% else %}
                <form action="{% url 'priv:login' %}" method='POST' id='loginForm' class='form-horizontal' autocomplete='off'>
                {% endif %}
                    {% csrf_token %}
                    {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                    {% endfor %}
                    <div class="form-inner panel-body">
                        <legend>Please Login</legend>
                        <!-- loop through the form to generate the username and password field -->

                        {% for field in form.visible_fields %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>

                            <div class="col-sm-10">
                                {{ field }}
                            </div>

                            {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        </div>
                        {% endfor %}

                        <!-- End of loop -->
                    </div>
                    <footer class="signin-actions panel-footer">
                        <input class="btn btn-primary" type='submit' id="submit" value='Login'/>
                        <a class="btn btn-primary" href="{% url 'home' %}">Exit</a>
                    </footer>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

hda_privileged/templates/hda_privileged/privdashboard.html
{% extends 'hda_privileged/base.html' %}
{% load staticfiles %}
{% block content %}

  <head>
    <!-- Make health indicator selected same color as navbar -->
    <style>.nav-pills>li.active>a, .nav-pills>li.active>a:focus{ background-color: #69899f; color: #d7e2e9;}</style>
  </head>

<!-- Column to list clickable indicators from db -->
<div class="row">
  <div class="col-sm-3">
    <div class="page-header"><h1><small>Indicators</small></h1></div>
      <!--button to reset and display all indicators-->
      <a role="button"
          href="{% url 'priv:dashboard1' %}"
          class="btn btn-primary btn-med"
          style="background-color:#69899f;color: #d7e2e9;">Reset Selection</a>
      <!-- Stack indicators vertically -->
      <ul class="nav nav-pills nav-stacked">
        <!--add a space to better align left and right column data-->
        <br/>
        <table class="table">
          {% for ind in indicators %}
          <!-- Align indicator and edit button horizontally -->
              <tr>
                  <td role="presentation" style="border:none" class="{% if selected_indicator and selected_indicator == ind %}active{% endif %}">
                    <a href="{% url 'priv:dashboardselected' ind.id %}">{{ ind.name }}</a>
                  </td>
                  <td role="presentation" style="border:none">
                    <a href="{% url 'priv:updateIndicator' ind.id %}"><i class="fa fa-edit" style="font-size:10px; color:#69899f;" title="Edit Indicator Name"></i></a>
                  </td>
                  <td role="presentation" style="border:none">
                    <a href="{% url 'priv:deleteIndicator' ind.id %}"><i class="fa fa-remove" style="font-size:15px; color:red;" title="Delete Indicator"></i></a>
                  </td>
              </tr>
          {% endfor %}
        </table>
      <br/>
      <!-- Button to add a new indicator -->
      <a role="button"
        href="{% url 'priv:createIndicator' %}"
        class="btn btn-primary btn-med"
        style="background-color:#69899f;color: #d7e2e9;">Add Indicator</a>
        <br/>
  </div>

    <!-- Space between columns -->
    <div class="col-sm-1"></div>

    <!-- File list for specific indicator viewable by clickable indicators -->
    <div class="col-sm-8">
      <div class="page-header">
        <h1><small>{{ indicator_message }}</small></h1>
      </div>
      {% csrf_token %}
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">Year</th>
              <th scope="col">Upload Date</th>
              <th scope="col">User</th>
              <th scope="col">File</th>
            </tr>
          </thead>
          <tbody>
            {% for ds in datasets %}
            <tr>
              <td>{{ ds.year }}</td>
              <td>{{ ds.source_document.uploaded_at }}</td>
              <td>{{ ds.source_document.user }}</td>
              <td>{{ ds.source_document.file }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
</div>
{% endblock %}

hda_privileged/templates/hda_privileged/update_metric_form.html
{% extends 'hda_privileged/base.html' %}

{% block content %}

{% comment %} Wrap the form in a panel for appearance {% endcomment %}
<div class='panel panel-primary'>

  <div class="panel-heading" style="background-color:#69899f;color: #d7e2e9;">
    <h3 class="panel-title">Update a health indicator</h3>
  </div>

  <div class="panel-body">
    <p>Updating a health indicator allows you to change the indicator name text. Health indicator names should be unique. Associated data sets will retain their association to the updated indicator.</p>
    <form method="post" class='form-inline'>{% csrf_token %}
   
        <!-- Django renders p tags in HTML -->
        {{ form.as_p }}
        <br/>
        <br/>    
        <button type="submit" class="btn btn-success" style="background-color:#69899f;color: #d7e2e9;">Save changes</button>
        <input class='btn btn-primary' type="button"  style="background-color:#69899f;color: #d7e2e9;" value='Cancel' onclick="window.history.back()"/>
    </form>
  </div>
</div>  
{% endblock %}

hda_privileged/templates/hda_privileged/upload_complete.html
{% extends 'hda_privileged/base.html' %}

{%block title%}Upload Health Data{%endblock%}

{% block content %}

<div class="container">
  <div class="jumbotron">
    <h2>Upload done</h2>
  </div>
</div>

{% endblock %}

{% block javascript%}
{%endblock%}

hda_privileged/templates/hda_privileged/upload_metric.html
{% extends 'hda_privileged/base.html' %}

{% block title %}Upload Health Data{% endblock %}

{% block content %}

    <div class="jumbotron">
        <h2>Upload your Metric data here</h2>

        {% comment %}
      Show any messages added to the context
      by using Bootstrap alert components
      {% endcomment %}
        <div class='form-group'>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        {% if 'error' not in message.tags %}
                            <div
                                    class="alert alert-{{ message.level_tag }}"
                                    role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </ul>
                <ul class="messages">
                    <div class="label-warning">The following counties/states combinations are invalid:</div>

                        <table class="table table-responsive table-hover table-bordered">
                            {% for county,state in invalid_counties_and_states.items  %}

                                    <tr>
                                    <td> {{ county}}</td><td>{{ state }}</td></tr>

                            {% endfor %}
                        </table>

                </ul>
            {% endif %}
        </div>


        <form
                class="form-horizontal"
                method="POST"
                enctype="multipart/form-data"
                action="{% url 'priv:uploadData' %}">
            {% csrf_token %}

            {% for field in form.visible_fields %}
                {% comment %}
          An unordered list of validation messages
          {% endcomment %}
                {{ field.errors }}

                <div {% if field.errors %} class="form-group has-error" {% else %} class="form-group" {% endif %}>

                    {% comment %} Label associated to the input w/ id_for_label {% endcomment %}
                    <label class="col-sm-2 control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>

                    {% comment %} The actual field/input element {% endcomment %}
                    <div class="col-sm-10">
                        {% if field == form.column_format %}
                            {% for radio in field %}
                                <div class="radio">
                                    {{ radio }}
                                </div>
                            {% endfor %}
                        {% else %}
                            {{ field }}
                        {% endif %}

                        {% comment %}
            Not using aria-describedby (but should be!) to link the field to its help text - 
            not sure how to inject that attribute into the django field output above
            {% endcomment %}
                        {% if field.help_text %}
                            <span class="help-block">{{ field.help_text | safe }}</span>
                        {% endif %}
                    </div>

                </div>
            {% endfor %}

        <button type="submit" class="btn btn-primary" onclick="TimeoutNow();" >Upload</button>
        <input class='btn btn-primary' onclick="window.history.back()" type="button" value='Cancel'/>
          <form>
              <!-- <input type="button" value="Upload" class="btn-primary" onclick="TimeoutNow();" /> -->

            </form>


        </form>
    </div>

{% endblock %}

{% block javascript %}
{% endblock %}